import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { I18nProvider } from '@/service/i18n';
import Header from '@/app/components/Layout/Header';
import './globals.css';
import { AppProps } from 'next/app'

const font = localFont({ src: '../../public/fonts/Vazirmatn[wght].ttf' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type Props = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: Props) {
  return (
    <html lang='en'>
      <body className={font.className}>
        <I18nProvider locale='fa'>
          <Header />

          <main className='flex min-h-screen flex-col items-center justify-between'>
            {children}
          </main>
        </I18nProvider>
      </body>
    </html>
  );
}
